apiVersion: v1
kind: Service
metadata:
  name: service-registry-backup
  namespace: myproject
  selfLink: /api/v1/namespaces/myproject/services/service-registry-backup
  uid: 8a4732ec-6b79-11e7-9839-c6ad6b1b6a10
  resourceVersion: '39293'
  creationTimestamp: '2017-07-18T05:25:41Z'
  labels:
    app: service-registry-backup
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  ports:
    - name: 8761-tcp
      protocol: TCP
      port: 8761
      targetPort: 8761
  selector:
    deploymentconfig: service-registry-backup
  clusterIP: 172.30.191.171
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}